version: '3.8'

services:
    web:
      build:
          context: ./services/web
          dockerfile: Dockerfile.prod
      command: gunicorn --workers=2 --bind 0.0.0.0:5000 project:app
      expose:
          - 5000
      deploy:
          mode: replicated
          replicas: 2
      env_file:
          - ./.env.prod
      depends_on:
          - db
    db:
      image: postgres:14.5
      volumes:
          - postgres_data_prod:/var/lib/postgresql/data
      env_file:
          - ./.env.prod.db
    nginx:
      build: ./services/nginx
      ports:
          - 1337:80
      depends_on:
          - web

volumes:
    postgres_data_prod:
