version: '3.8'

services:
  web:
    build: ./services/web
    command: flask run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
      image: postgres:14.5
      volumes:
          - postgres_data:/var/lib/postgresql/data
      environment:
          - POSTGRES_USER=solera_admin
          - POSTGRES_PASSWORD=solera_pass
          - POSTGRES_DB=solera_db

volumes:
  postgres_data:
