version: '3.8'

services:
  web:
    build:
        context: ./services/web
        dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 project:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
      image: postgres:14.5
      volumes:
          - postgres_data_prod:/var/lib/postgresql/data
      env_file:
          - ./.env.prod.db

volumes:
  postgres_data_prod:
